### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 when install hyper-engine

### ISSUE THREAD

**Issue by zjy8006** [maxim5/hyper-engine#10]
system:
platform: win10 1709
anaconda: 5.1.0
python:3.6.4
tensorflow:1.8
The following error occurred while installing the hyper-engine:
```
(base) C:\Users\Samantha>pip install hyperengine
Collecting hyperengine
  Using cached https://files.pythonhosted.org/packages/d7/de/cc05d99e18ddb74012bf5d5ec8f7932fd5d667a5373c576d26dfad6f598a/hyperengine-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Samantha\AppData\Local\Temp\pip-install-7qdfd7at\hyperengine\setup.py", line 21, in <module>
        long_description = read('README.rst'),
      File "C:\Users\Samantha\AppData\Local\Temp\pip-install-7qdfd7at\hyperengine\setup.py", line 9, in read
        return open(os.path.join(os.path.dirname(__file__), file_)).read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 8018: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Samantha\AppData\Local\Temp\pip-install-7qdfd7at\hyperengine\
```
Any idea about this? Thanks for your time!

**Comment by maxim5** [comment]
Thanks for report. This is so strange, readme file is all ASCII. I'll try
to reproduce it when I have some free time
